#!/bin/sh
nohup /THFS/home/paratera09/0-software/java/jdk-9.0.1/bin/java -jar -Xmx10g /THFS/home/paratera09/0-software/cash_v2.2.0/cash.jar --Case:Mutation ./3AMU/Chr1.sorted.bam,./A104AMU/Chr1.sorted.bam  --Control:WildType ./3AWT/Chr1.sorted.bam,./A104AWT/Chr1.sorted.bam --GTF ./Zea_mays.AGPv4.37.gtf --Output ./Chr1-M.W.cash.result &
nohup /THFS/home/paratera09/0-software/java/jdk-9.0.1/bin/java -jar -Xmx10g /THFS/home/paratera09/0-software/cash_v2.2.0/cash.jar --Case:Mutation ./3AMU/Chr2.sorted.bam,./A104AMU/Chr2.sorted.bam  --Control:WildType ./3AWT/Chr2.sorted.bam,./A104AWT/Chr2.sorted.bam --GTF ./Zea_mays.AGPv4.37.gtf --Output ./Chr2-M.W.cash.result &
nohup /THFS/home/paratera09/0-software/java/jdk-9.0.1/bin/java -jar -Xmx10g /THFS/home/paratera09/0-software/cash_v2.2.0/cash.jar --Case:Mutation ./3AMU/Chr3.sorted.bam,./A104AMU/Chr3.sorted.bam  --Control:WildType ./3AWT/Chr3.sorted.bam,./A104AWT/Chr3.sorted.bam --GTF ./Zea_mays.AGPv4.37.gtf --Output ./Chr3-M.W.cash.result &
nohup /THFS/home/paratera09/0-software/java/jdk-9.0.1/bin/java -jar -Xmx10g /THFS/home/paratera09/0-software/cash_v2.2.0/cash.jar --Case:Mutation ./3AMU/Chr4.sorted.bam,./A104AMU/Chr4.sorted.bam  --Control:WildType ./3AWT/Chr4.sorted.bam,./A104AWT/Chr4.sorted.bam --GTF ./Zea_mays.AGPv4.37.gtf --Output ./Chr4-M.W.cash.result &
nohup /THFS/home/paratera09/0-software/java/jdk-9.0.1/bin/java -jar -Xmx10g /THFS/home/paratera09/0-software/cash_v2.2.0/cash.jar --Case:Mutation ./3AMU/Chr5.sorted.bam,./A104AMU/Chr5.sorted.bam  --Control:WildType ./3AWT/Chr5.sorted.bam,./A104AWT/Chr5.sorted.bam --GTF ./Zea_mays.AGPv4.37.gtf --Output ./Chr5-M.W.cash.result &
nohup /THFS/home/paratera09/0-software/java/jdk-9.0.1/bin/java -jar -Xmx10g /THFS/home/paratera09/0-software/cash_v2.2.0/cash.jar --Case:Mutation ./3AMU/Chr6.sorted.bam,./A104AMU/Chr6.sorted.bam  --Control:WildType ./3AWT/Chr6.sorted.bam,./A104AWT/Chr6.sorted.bam --GTF ./Zea_mays.AGPv4.37.gtf --Output ./Chr6-M.W.cash.result &
nohup /THFS/home/paratera09/0-software/java/jdk-9.0.1/bin/java -jar -Xmx10g /THFS/home/paratera09/0-software/cash_v2.2.0/cash.jar --Case:Mutation ./3AMU/Chr7.sorted.bam,./A104AMU/Chr7.sorted.bam  --Control:WildType ./3AWT/Chr7.sorted.bam,./A104AWT/Chr7.sorted.bam --GTF ./Zea_mays.AGPv4.37.gtf --Output ./Chr7-M.W.cash.result &
nohup /THFS/home/paratera09/0-software/java/jdk-9.0.1/bin/java -jar -Xmx10g /THFS/home/paratera09/0-software/cash_v2.2.0/cash.jar --Case:Mutation ./3AMU/Chr8.sorted.bam,./A104AMU/Chr8.sorted.bam  --Control:WildType ./3AWT/Chr8.sorted.bam,./A104AWT/Chr8.sorted.bam --GTF ./Zea_mays.AGPv4.37.gtf --Output ./Chr8-M.W.cash.result &
nohup /THFS/home/paratera09/0-software/java/jdk-9.0.1/bin/java -jar -Xmx10g /THFS/home/paratera09/0-software/cash_v2.2.0/cash.jar --Case:Mutation ./3AMU/Chr9.sorted.bam,./A104AMU/Chr9.sorted.bam  --Control:WildType ./3AWT/Chr9.sorted.bam,./A104AWT/Chr9.sorted.bam --GTF ./Zea_mays.AGPv4.37.gtf --Output ./Chr9-M.W.cash.result &
nohup /THFS/home/paratera09/0-software/java/jdk-9.0.1/bin/java -jar -Xmx10g /THFS/home/paratera09/0-software/cash_v2.2.0/cash.jar --Case:Mutation ./3AMU/Chr10.sorted.bam,./A104AMU/Chr10.sorted.bam  --Control:WildType ./3AWT/Chr10.sorted.bam,./A104AWT/Chr10.sorted.bam --GTF ./Zea_mays.AGPv4.37.gtf --Output ./Chr10-M.W.cash.result &
nohup /THFS/home/paratera09/0-software/java/jdk-9.0.1/bin/java -jar -Xmx10g /THFS/home/paratera09/0-software/cash_v2.2.0/cash.jar --Case:Mutation ./3AMU/scaffold.sorted.bam,./A104AMU/scaffold.sorted.bam  --Control:WildType ./3AWT/scaffold.sorted.bam,./A104AWT/scaffold.sorted.bam --GTF ./Zea_mays.AGPv4.37.gtf --Output ./scaffold-M.W.cash.result &

